baseURL: "https://mdmahadi-hasan.github.io/" 
title: MD MAHADI HASAN
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /papers/
          weight: 1
        - name: Data Projects
          url: /courses/
          weight: 2
        - name: Readings
          url: /readings/
          weight: 3
       
        

params:
    description: "Md Mahadi Hasan is a master's student of Applied Economics at NDSU. His research covers Applied Econometrics, Applied Microeconoomics & environmental economics."
    author: Md Mahadi Hasan
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: MD MAHADI HASAN
          subtitle: "Hello! I'm Mahadi, a Master's student in the **Department of Agribusiness and Applied Economics** at North Dakota State University, and a Graduate Research Assistant. My work and research interests lie in **Applied Econometrics, Applied Microeconomics, Behavioral Economics, and Environmental Economics.** I am dedicated to transforming **complex data** into impactful, real-world insights through compelling storytelling, demonstrating the practical implementation of economic theories, and evaluating **policies.** If you're interested in collaboration, please feel free to contact me."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: MD MAHADI HASAN
          buttons:
            - name: Research
              url: /papers/
            - name: Data Projects
              url: /courses/
            - name: Readings
              url: /readings/
         
            

    socialIcons:
        - name: Email
          url: mdmahadi.hasan.1@ndsu.edu
        - name: GitHub
          url: https://github.com/MdMahadi-hasan
       

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "MD MAHADI HASAN"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
